mlibrary/mlibrary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('novels.urls')),
]

mlibrary/novels/urls.py
from django.urls import path
from . import views

app_name = 'novels'
urlpatterns=[
    path('',views.index, name='index'),
    path('bookcase/<int:bookcase_id>/',views.detail_bookcase, name='detail_bookcase'),
    path('bookcase/make/',views.make_bookcase,name='make_bookcase'),
    path('novel/upload/<int:bookcase_id>', views.upload_novel, name='upload_novel'),
    path('novel/<int:novel_id>/',views.detail_novel, name='detail_novel')

    
]

mlibrary/novels/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Bookcase(models.Model):
    name = models.CharField(max_length=500)

class Novel(models.Model):
    bookcase= models.ForeignKey(Bookcase, on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    title = models.CharField(max_length=500)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateField()
    file = models.FileField(upload_to='uploads/',max_length=500, null=True)

    def __str__(self):
        return self.title

mlibrary/novels/forms.py
from django import forms
import datetime

class BookcaseForm(forms.Form):
    bookcase_name = forms.CharField(label='bookcase name', max_length=500)

class NovelForm(forms.Form):
    title = forms.CharField(max_length=500)
    author = forms.CharField(max_length=200)
    published_date = forms.DateField(
            widget=forms.SelectDateWidget(
                empty_label=("Choose Year", "Choose Month", "Choose Day"),
                years=range(1985, datetime.date.today().year+10)
                ),
            )
    file = forms.FileField()

mlibrary/novels/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Bookcase, Novel
from .forms import BookcaseForm, NovelForm

# Create your views here.

def index(request):
    bookcase_list = Bookcase.objects.all()
    context = {
        'bookcase_list' : bookcase_list,
    }
    return render(request,'novels/index.html',context)

def make_bookcase(request):
    if request.method == 'POST':
        print('post')
        form = BookcaseForm(request.POST)
        if form.is_valid():
            bookcase = Bookcase(name=form.cleaned_data['bookcase_name'])
            bookcase.save()
            return HttpResponseRedirect('/')
    else:
        form = BookcaseForm()

    return render(request, 'novels/make_bookcase.html',{'form':form})

def upload_novel(request, bookcase_id):
    if request.method=='POST':
        print('upload_novel post bookcase_id' ,bookcase_id)
        form = NovelForm(request.POST,request.FILES)
        if form.is_valid():
            bookcase = Bookcase.objects.get(pk=bookcase_id)
            novel = Novel(file=request.FILES['file'])
            novel.bookcase = bookcase
            novel.author = form.cleaned_data['author']
            novel.title = form.cleaned_data['title']
            novel.published_date = form.cleaned_data['published_date']
            novel.save()

            return HttpResponseRedirect(f'/bookcase/{bookcase.id}')
    else:
        form = NovelForm()
        bookcase = get_object_or_404(Bookcase, pk=bookcase_id)
        context = {
            'bookcase':bookcase
        }
    print(context)
    return render(request, 'novels/upload_novel.html',{'form':form ,'bookcase':bookcase})

def detail_bookcase(request, bookcase_id):
    bookcase = get_object_or_404(Bookcase, pk=bookcase_id)
    return render(request, 'novels/detail_bookcase.html', {'bookcase':bookcase})

def detail_novel(request, novel_id):
    novel = get_object_or_404(Novel, pk=novel_id)
    return render(request, 'novels/detail_novel.html', {'novel':novel})

mlibrary/novels/templates/novels/base.html
{% load staticfiles %}

<html>
  <head>
    <title> MinGyu Kim's Library</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>

</html>

mlibrary/novels/templates/novels/detail_bookcase.html
{% extends 'novels/base.html' %}
{% block content %}
  <div class="page-header">
    <h1>{{ bookcase.name }} </h1>
  </div>
  <div class="page-text">
    <ul>
    {% for novel in bookcase.novel_set.all %}
    <li><a href="{% url 'novels:detail_novel' novel.id %}">{{ novel.title }}</a></li>
    {% endfor %}
    </ul>
  </div>
  <p><a href="{% url 'novels:index' %}">상위로</a></p>
  <a href="{% url 'novels:upload_novel' bookcase.id %}">소설 업로드</a>
{% endblock %}

mlibrary/novels/templates/novels/detail_novel.html
{% extends 'novels/base.html' %}
{% block content %}
  <div class="border-bottom">
    <h1> {{ novel.title }} </h1>
    <p>  {{ novel.author}} {{ novel.published_date }} </p>
  </div>
  <div class="page-text">
    <p>
    {{ novel.file.read.decode | linebreaksbr }}
    </p>
  </div>
  <a href="{% url 'novels:detail_bookcase' novel.bookcase.id %}"> 상위로</a>
{% endblock %}

mlibrary/novels/templates/novels/index.html
{% extends 'novels/base.html' %}
{% block content %}
  <div class="page-header">
    <h1> Welcome to M's Library</h1>
  </div>
  <div class="page-text">
    <div class="col-md-8">
      <h2> The Bookcase List </h2>
      {% if bookcase_list %}
          <ul>
          {% for bookcase in bookcase_list %}
          <li><a href="{% url 'novels:detail_bookcase' bookcase.id %}"> {{ bookcase.name }}</a></li>
          {% endfor %}
          </ul>
      {% else %}
          <p> no novels </p>
      {% endif %}

      <a href="{% url 'novels:make_bookcase' %}">책장 만들기</a>
    </div>
  </div>
{% endblock %}

mlibrary/novels/templates/novels/make_bookcase.html
<form action=" {% url 'novels:make_bookcase'%}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

mlibrary/novels/templates/novels/upload_novel.html
<h1> uploaing on {{bookcase.name}} </h1>
<form action="{% url 'novels:upload_novel' bookcase.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }} 
    <input type='hidden' name='bookcase_id' value="{{ bookcase.id }}" >
    <input type="submit" value='ok'>
</form>